spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql:///test?characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
    username: root
    password: 123456
  jpa:
    show-sql: true
